apiversion: v1
kind: verify-report
metadata:
    tool:
        verifier-version: 1.14.0
        profile:
            VendorType: partner
            version: v1.3
        reportDigest: uint64:3574555437038229849
        chart-uri: N/A
        digests:
            chart: sha256:37603e7ed5f8294520746760d427fddbc13a6d1b376ace25a6557c4d1b7e9172
            package: 19f736afc5b7900f037c185912e4b6b36878fb8870fcfb73448074ec48b09b12
        lastCertifiedTimestamp: "2026-02-25T17:42:14.964429+00:00"
        testedOpenShiftVersion: "4.14"
        supportedOpenShiftVersions: '>=4.1'
        webCatalogOnly: true
    chart:
        name: remote-active-worker-ubi
        home: ""
        sources: []
        version: 3.52.29
        description: Active Worker Helm Chart for remote active worker deployments
        keywords: []
        maintainers: []
        icon: ""
        apiversion: v2
        condition: ""
        tags: ""
        appversion: 2.40.3-ubi
        deprecated: false
        annotations:
            charts.openshift.io/name: Remote Active Testing Worker
        kubeversion: '>=1.0.0-0'
        dependencies: []
        type: application
    chart-overrides: ""
results:
    - check: v1.0/not-contain-csi-objects
      type: Mandatory
      outcome: PASS
      reason: CSI objects do not exist
    - check: v1.0/not-contains-crds
      type: Mandatory
      outcome: PASS
      reason: Chart does not contain CRDs
    - check: v1.0/signature-is-valid
      type: Mandatory
      outcome: SKIPPED
      reason: 'Chart is not signed : Signature verification not required'
    - check: v1.1/has-kubeversion
      type: Mandatory
      outcome: PASS
      reason: Kubernetes version specified
    - check: v1.0/helm-lint
      type: Mandatory
      outcome: PASS
      reason: Helm lint successful
    - check: v1.0/required-annotations-present
      type: Mandatory
      outcome: PASS
      reason: All required annotations present
    - check: v1.0/contains-values-schema
      type: Mandatory
      outcome: PASS
      reason: Values schema file exist
    - check: v1.0/contains-values
      type: Mandatory
      outcome: PASS
      reason: Values file exist
    - check: v1.0/has-notes
      type: Optional
      outcome: PASS
      reason: Chart does contain NOTES.txt
    - check: v1.0/is-helm-v3
      type: Mandatory
      outcome: PASS
      reason: API version is V2, used in Helm 3
    - check: v1.0/chart-testing
      type: Mandatory
      outcome: PASS
      reason: Chart tests have passed
    - check: v1.0/has-readme
      type: Mandatory
      outcome: PASS
      reason: Chart has a README
    - check: v1.1/images-are-certified
      type: Mandatory
      outcome: PASS
      reason: 'Image is Red Hat certified : us-central1-docker.pkg.dev/noname-artifacts/nns-docker/active-worker:2.40.3-ubi'
    - check: v1.0/contains-test
      type: Mandatory
      outcome: PASS
      reason: Chart test files exist
